name: Deployment pipeline

on: [push]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: dependencies install 
        run: yarn  
      - name: lint
        run: yarn eslint
      - name: build
        run: yarn build
      - name: test
        run: yarn test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: yarn run test:e2e
          start: yarn run start-prod
          wait-on: http://localhost:5000
  
